# Generated by Django 3.2.8 on 2021-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='role',
            field=models.CharField(default='regular', max_length=50, null=True),
        ),
    ]
