# Generated by Django 3.2.8 on 2021-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('rating', models.FloatField(default=5)),
                ('num_reviews', models.IntegerField(verbose_name=0)),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
