# Generated by Django 3.2.8 on 2021-10-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_adventurelocation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurelocation',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
