# Generated by Django 3.2.8 on 2021-10-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_auto_20211025_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventuretrip',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
