# Generated by Django 3.2.8 on 2021-11-01 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_adventuretrip_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurelocation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='adventuretrip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
