# Generated by Django 3.2.8 on 2021-12-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0011_adventurelocation_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventuretrip',
            name='adventureLocation',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='adventures.adventurelocation'),
            preserve_default=False,
        ),
    ]
